# Generated by Django 4.1.2 on 2022-11-08 06:51

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
